##local RabbitMq 개발용
rabbitmq-host: "localhost"
rabbitmq-username: "guest"
rabbitmq-password: "guest"
rabbitmq-port: 5672
##local Redis 개발용
redis-host: "localhost"
redis-port: 6379
redis-password: "default"

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    io.micrometer: debug

