spring:
  config:
    activate:
      on-profile: dev

##local RabbitMq 개발용
rabbitmq-host: "localhost"
rabbitmq-username: "guest"
rabbitmq-password: "guest"
rabbitmq-port: 5672
##local Redis 개발용
redis-host: "localhost"
redis-port: 6379
redis-password: "default"
##Naver 검색 api
NAVER-SEARCH-ID: aY3htNCRURon01pEVu8z
NAVER-SEARCH-PASSWORD: secret

### Eureka 등록
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


GATEWAY-SERVICE-URL: "http://localhost:9777/"