management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    io.micrometer: debug

#rabbitmq-host: "localhost"
#rabbitmq-username: "guest"
#rabbitmq-password: "guest"
#rabbitmq-port: 5672