management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true


nhn:
  cloud:
    keyManager:
      appkey: 2SxwmBzUfnqJaA2A
      redisKey: 60427297022b4bdb9650789537e4b945
      oauth2Key: 86844e05ca8540648193ae8935acd787
      naverBookKey: ca76216877d545a198162092ca6bf726
      rabbitMQKey: 5070b197613e4db6a73e9db96c54789f
      userAccessKey: J9VxQFQEsmerR1n7FeJ6
      secretAccessKey: zZEVopUHt6dxgRMt

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    io.micrometer: debug

  #로그 크러쉬 정보
  logstash:
    host: 133.186.241.167
    platform: NovaBook-Front-Dev
    url: https://api-logncrash.cloud.toast.com/v2/log
    projectName: Xyx7DoyszcG66ULx
    projectVersion: 1.0.0
    logVersion: v2
    logSource: http
    logType: log
    secretKey: JsGDL5oTWPImKY8nag9igsUAdnUOvLMI
