spring:
  application:
    name: novabook_front
  thymeleaf:
    prefix: classpath:/templates/
  #기본으로 실행할 프로필
  profiles:
    include: dev

  # Feign client url
  cloud:
    openfeign:
      client:
        config:
          pointClient:
            url: http://localhost:9777/api/v1/store/point/histories

  # RabbitMQ config
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3000
          max-interval: 10000
          max-attempts: 3
          multiplier: 2.0

rabbitmq:
  queue:
    couponCreateNormal: nova.coupon.create.normal.queue
    couponCreateHighTraffic: nova.coupon.create.hightraffic.queue
    couponRegisterNormal: nova.coupon.register.normal.queue
    couponRegisterHighTraffic: nova.coupon.register.hightraffic.queue
    deadLetter: nova.coupon.deadletter.queue
  exchange:
    couponOperation: nova.coupon.operation.exchange
    deadLetter: nova.coupon.deadletter.exchange
  routing:
    couponCreateNormal: coupon.create.normal
    couponCreateHighTraffic: coupon.create.hightraffic
    couponRegisterNormal: coupon.register.normal
    couponRegisterHighTraffic: coupon.register.hightraffic

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/