spring:
  config:
    activate:
      on-profile: prod

### Eureka 등록
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://novabook-eureka-service:8761/eureka