spring:
  profiles: set1
server:
  port: 8081

---
spring:
  profiles: set2

server:
  port: 8082

---
spring:
  profiles: set3

server:
  port: 8082

---
spring:
  profiles: set4

server:
  port: 8082